<a href="https://colab.research.google.com/github/vnzhere/Python-/blob/main/np%2C_pd%2Cmatplotlib%2Cseaborn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy---- Numerical python

Advantages of numpy Arrays
1. Allows several mathematical operations
2. faster operations


In [1]:
import numpy as np


List vs Numpy--- time taken

In [4]:
from time import process_time

time taken by a list

In [3]:
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list= [1+5 for i in python_list]

end_time= process_time()

print(end_time-start_time)

0.0007694510000000321


In [9]:
from time import process_time
import numpy as np # Ensure numpy is imported

np_array = np.arange(10000)

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time-start_time)

0.00043127100000006635


Numpy arrays

In [10]:
#list

list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
#creating a 1D array

a= np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [14]:
a.shape #we have 4 columns

(4,)

In [15]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape #rows-2, 4-columns

(2, 4)

In [17]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays


In [20]:
# create a numpy array of zeroes

x= np.zeros((4,5)) #shape of arrays
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#creating numpy arrays of ones

y= np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#creating of array of particular values

z= np.full((5,4),5)
print(z)  #4x5 array with all the values as 5

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
#creating identity matrix

v= np.eye(3) #only 4x4 or 5x5 will work
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
