<a href="https://colab.research.google.com/github/vnzhere/Python-/blob/main/np%2C_pd%2Cmatplotlib%2Cseaborn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy---- Numerical python

Advantages of numpy Arrays
1. Allows several mathematical operations
2. faster operations


In [3]:
import numpy as np


List vs Numpy--- time taken

In [ ]:
from time import process_time

time taken by a list

In [ ]:
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list= [1+5 for i in python_list]

end_time= process_time()

print(end_time-start_time)

0.0007694510000000321


In [ ]:
from time import process_time
import numpy as np # Ensure numpy is imported

np_array = np.arange(10000)

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time-start_time)

0.00043127100000006635


Numpy arrays

In [ ]:
#list

list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1D array

a= np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
a.shape #we have 4 columns

(4,)

In [ ]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape #rows-2, 4-columns

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays


In [ ]:
# create a numpy array of zeroes

x= np.zeros((4,5)) #shape of arrays
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating numpy arrays of ones

y= np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating of array of particular values

z= np.full((5,4),5)
print(z)  #4x5 array with all the values as 5

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#creating identity matrix

v= np.eye(3) #only 4x4 or 5x5 will work
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
#create a numpy array with random values (gives value between 0 and 1)

b= np.random.random((3,4))
print(b)

[[0.88677564 0.68446651 0.26958823 0.13790366]
 [0.3851692  0.5750927  0.57248179 0.30179101]
 [0.01075224 0.75964836 0.91771351 0.5007105 ]]


In [6]:
#random integer values array within a specific range

import numpy as np
c= np.random.randint(10, 100, size=(3,5)) # specific range (low, high), matrix dimension
print(c)


[[97 24 26 40 32]
 [43 13 38 10 14]
 [66 74 40 59 76]]


In [7]:
#create an array of evenly spaced values
# evenly spaced ---- specifying the no. of values

d= np.linspace(10,30,5) #start, end, number of values
print(d)

[10. 15. 20. 25. 30.]


In [8]:
# array of evenly spaced values ---- specifying the steps
#between particular range

e= np.arange(10,30,5) #start, end, step
print(e)

[10 15 20 25]


In [10]:
#convert a list to a numpy array

list2 = [10,20,30,40,50]

np_array= np.asarray(list2)
print(np_array)
type(np_array)


[10 20 30 40 50]


numpy.ndarray

Analyzing a numpy array

In [11]:
c =  np.random.randint(10,90, (5,5))
print(c)

[[26 69 27 25 52]
 [34 23 66 27 78]
 [53 39 73 83 23]
 [79 53 48 22 51]
 [50 23 57 52 84]]


In [12]:
#array dimensions

print(c.shape)


(5, 5)


In [13]:
#number of dimensions
print(c.ndim)

2


In [14]:
#number of elements in an array
print(c.size)

25


In [15]:
#checking the datatype of values in the array
print(c.dtype)

int64


Mathematical operations on an np array


In [16]:

list1=[1,2,3,4,5]
list2= [6,7,8,9,10]

print(list1 + list2) #concatenate or join 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [18]:
a = np.random.randint(0,10, size=(3,3))
b = np.random.randint(10,20, size=(3,3))


In [19]:
print(a)
print(b)

[[1 8 3]
 [0 9 5]
 [7 9 8]]
[[18 16 14]
 [19 17 16]
 [11 16 13]]


In [20]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[19 24 17]
 [19 26 21]
 [18 25 21]]
[[-17  -8 -11]
 [-19  -8 -11]
 [ -4  -7  -5]]
[[ 18 128  42]
 [  0 153  80]
 [ 77 144 104]]
[[0.05555556 0.5        0.21428571]
 [0.         0.52941176 0.3125    ]
 [0.63636364 0.5625     0.61538462]]


In [21]:
#print new values of a and b
a = np.random.randint(0,10, size=(3,3))
b = np.random.randint(10,20, size=(3,3))

In [23]:
print(a)
print(b)

[[9 3 3]
 [4 9 7]
 [6 5 3]]
[[18 10 19]
 [15 14 13]
 [18 11 14]]


In [24]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[27 13 22]
 [19 23 20]
 [24 16 17]]
[[ -9  -7 -16]
 [-11  -5  -6]
 [-12  -6 -11]]
[[162  30  57]
 [ 60 126  91]
 [108  55  42]]
